version: '3.8' # 개발용 docker-compose 파일입니다.

services:
  database:
    image: mysql
    container_name: database
    environment:
      - MYSQL_DATABASE=file_extensions
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - "./database:/var/lib/mysql"
    ports:
      - "3306:3306"
