spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: src/main/resources/files
